import { createFileRoute } from "@tanstack/react-router";
import { ServiceDetail, OfferingDetail } from "@/components/site/ServiceDetail";

const detailedOfferings: OfferingDetail[] = [
  {
    title: "1. Hierarchical Agent Grids & Supervisor Orchestrators",
    subtitle: "Goal-directed routing and dynamic team orchestration structures",
    description: "Deploying multi-agent grid systems (like LangGraph, CrewAI, AutoGen) that route complex business operations into role-specific agent hierarchies. We set up supervisor nodes that plan, delegate, compile, and validate outcomes generated by worker sub-agents.",
    keySituations: [
      "Monolithic single-agent loops crashing or losing state when executing multi-department workflows.",
      "Difficulty orchestrating concurrent tasks requiring specialized expertise (e.g. software QA vs data extraction).",
      "Runaway costs from agents repeating commands or losing context synchronization."
    ],
    keyStatistics: [
      "Task completion accuracy: Improved to 94.6% on complex inputs",
      "Orchestration cost overhead: Cut by 50% via hierarchical routing",
      "Agent coordination speed: < 80ms communication steps",
      "Workflow throughput: Expanded by 4x under parallel worker execution"
    ],
    offeringValue: "Decomposes complex, multi-day enterprise processes into discrete, deterministic agent tasks with high success rates.",
    expectedOutcomes: [
      "Stateful LangGraph/CrewAI multi-agent blueprints.",
      "Supervisor routing layers dynamically assigning tasks based on model capability scores.",
      "Task tracebooks illustrating state variables and communication logs between agents."
    ]
  },
  {
    title: "2. Consensus Deliberation & Collaborative Reasoning Hubs",
    subtitle: "Multi-agent debate protocols and automated consensus checkpoints",
    description: "Engineering collaborative reasoning clusters where agents debate outputs, cross-validate predictions, and require consensus approvals before gating high-stakes actions (such as code commits or financial reviews).",
    keySituations: [
      "AI assistants generating single-perspective, low-precision answers for high-risk audits.",
      "Lack of structured checks leading to invalid calculations or logic errors in automated outputs.",
      "Unchecked model biases skewing quantitative analysis or recommendations."
    ],
    keyStatistics: [
      "Deliberation check precision: 99.1% error suppression rate",
      "Debate cycle duration: Optimized under 1.2 seconds",
      "Bias skew indicators: Reduced by 85% through opposing-agent critiques",
      "Consensus gate auditability: 100% cryptographically logged"
    ],
    offeringValue: "Injects strict logical rigor, error correction, and multi-perspective validation into automated enterprise decisions.",
    expectedOutcomes: [
      "Debate graph architectures gating high-risk API and logic operations.",
      "Consensus verification modules logging votes, reasoning vectors, and validation scores.",
      "Human override gates allowing operators to break debate loops or review conflicts."
    ]
  }
];

export const Route = createFileRoute("/multi-agent-systems")({
  head: () => ({
    meta: [
      { title: "Multi-Agent Systems — Orchestrated AI Fleets | TrustGrid.AI" },
      { name: "description", content: "Coordinate fleets of specialized AI agents to deliver complex enterprise outcomes. Routing, planning, debate and consensus at production scale." },
      { property: "og:title", content: "Multi-Agent Systems | TrustGrid.AI" },
      { property: "og:description", content: "Orchestrated agent fleets for autonomous enterprise operations." },
      { property: "og:url", content: "/multi-agent-systems" },
    ],
    links: [{ rel: "canonical", href: "/multi-agent-systems" }],
  }),
  component: () => (
    <ServiceDetail
      eyebrow="Multi-Agent Orchestration"
      title="Orchestrating fleets of specialized AI agents"
      description="Multi-agent architectures that decompose complex business operations into specialist roles, coordinated through robust routing, planning and consensus protocols."
      outcomes={[
        { value: "94.6%", label: "Task Accuracy" },
        { value: "50%", label: "Orchestration Cost Cut" },
        { value: "4x", label: "Workflow Throughput" },
        { value: "99.1%", label: "Error Suppression Rate" },
      ]}
      capabilities={[
        { title: "Hierarchical Orchestration", desc: "Supervisor agents delegate to specialist worker agents." },
        { title: "Debate & Consensus", desc: "Multi-agent deliberation for high-stakes decisions." },
        { title: "Dynamic Routing", desc: "Skill-based and load-aware agent task routing." },
        { title: "Shared State", desc: "Conflict-free shared memory across concurrent agents." },
        { title: "Agent Marketplaces", desc: "Internal registries of approved enterprise agents." },
        { title: "Evaluation Harness", desc: "Continuous evaluation of multi-agent workflows." },
      ]}
      stack={["LangGraph", "CrewAI", "AutoGen", "Ray", "Redis", "Kafka", "Temporal"]}
      detailedOfferings={detailedOfferings}
    />
  ),
});
